import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Remove Press_Start_2P
import "./globals.css";
import Layout from "@/components/Layout"; // Import the custom Layout component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoMCP", // Updated title
  description: "Generated by create next app",
  icons: { // Added icon configuration
    icon: '/logo.png', // Path relative to the public directory
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cyberpunk">{/* Set data-theme to 'cyberpunk' */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Remove pixel font variable
      >
        <Layout>{children}</Layout> {/* Wrap children with Layout */}
      </body>
    </html>
  );
}
